# -*- coding: utf-8 -*-
"""Histogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-sWVCq8ZqAUeF5cyfcCtLldDfo19qUsx
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Baca gambar
img = cv2.imread('/content/drive/MyDrive/SEMESTER 5/Pengolahan Citra Digital/SESI 3/Bike.png')

# Konversi BGR ke RGB (karena OpenCV membaca dalam format BGR)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Konversi ke grayscale
img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)

# Tampilkan gambar original dan grayscale
plt.figure(figsize=(12, 4))

plt.subplot(121)
plt.imshow(img_rgb)
plt.title('Gambar Original (RGB)')
plt.axis('off')

plt.subplot(122)
plt.imshow(img_gray, cmap='gray')
plt.title('Gambar Grayscale')
plt.axis('off')

plt.show()

# Tampilkan histogram dari gambar grayscale
plt.figure(figsize=(10, 5))
plt.hist(img_gray.ravel(), bins=256, range=[0, 256])
plt.title('Histogram of Grayscale Image')
plt.xlabel('Pixel Intensity (0-255)')
plt.ylabel('Number of Pixels')
plt.show()

# Simpan gambar grayscale
cv2.imwrite('motor_grayscale.jpg', img_gray)